pyproject.toml, src/model_diagnostics/_utils/array.py, src/model_diagnostics/calibration/identification.py, src/model_diagnostics/calibration/plots.py, src/model_diagnostics/calibration/tests/test_identification.py
Solves #10.
- Case weights for `compute_bias`, `plot_bias`
- Use polars
- pyarrow and pandas remove as project dependency
=> Add case weights to compute_bias and plot_bias

src/model_diagnostics/calibration/identification.py, src/model_diagnostics/calibration/plots.py, src/model_diagnostics/scoring/__init__.py, src/model_diagnostics/scoring/scoring.py, src/model_diagnostics/scoring/tests/test_scoring.py
* add scoring module
* add HomogeneousExpectileScore
This partially addresses #2.
=> ENH add scoring functions

src/model_diagnostics/calibration/identification.py, src/model_diagnostics/calibration/tests/test_identification.py, src/model_diagnostics/scoring/__init__.py, src/model_diagnostics/scoring/scoring.py, src/model_diagnostics/scoring/tests/test_scoring.py
=> ENH add HomogeneousQuantileScore

.github/workflows/test.yml, src/model_diagnostics/_utils/array.py, src/model_diagnostics/calibration/plots.py, src/model_diagnostics/calibration/tests/test_plots.py
=> ENH bootstrap confidence intervals for reliability diagram

src/model_diagnostics/calibration/identification.py, src/model_diagnostics/calibration/tests/test_identification.py
=> ENH support NaN / Null feature values in compute_bias

src/model_diagnostics/calibration/identification.py, src/model_diagnostics/calibration/plots.py, src/model_diagnostics/scoring/scoring.py
The quality of the documentation is fantastic. I had to dig really hard to find those typos.
=> DOC fix typos

src/model_diagnostics/calibration/identification.py, src/model_diagnostics/calibration/tests/test_identification.py
This makes compute_bias return a deterministic dataframe for string and categorical features
=> FIX fix logic for string features with n_bins in compute_bias

src/model_diagnostics/calibration/plots.py, src/model_diagnostics/calibration/tests/test_plots.py
=> ENH plot null values in plot_bias

src/model_diagnostics/calibration/identification.py, src/model_diagnostics/scoring/__init__.py, src/model_diagnostics/scoring/scoring.py, src/model_diagnostics/scoring/tests/test_scoring.py
=> ENH add ElementaryScore

src/model_diagnostics/calibration/plots.py, src/model_diagnostics/calibration/tests/test_plots.py
Closes #64.
* Always use diamonds
* Add Null values to legend
* Null values always to the right
=> ENH plot_bias with Null values

pyproject.toml, src/model_diagnostics/__init__.py, src/model_diagnostics/calibration/identification.py, src/model_diagnostics/calibration/tests/test_identification.py, src/model_diagnostics/scoring/tests/test_scoring.py
=> FIX deprecation warnings of polars 0.19 groupby and replace

src/model_diagnostics/_utils/isotonic.py, src/model_diagnostics/calibration/identification.py, src/model_diagnostics/calibration/plots.py, src/model_diagnostics/scoring/plots.py, src/model_diagnostics/scoring/scoring.py, src/model_diagnostics/scoring/tests/test_scoring.py
=> FIX edge case in decompose for constant y

src/model_diagnostics/_utils/isotonic.py, src/model_diagnostics/scoring/scoring.py, src/model_diagnostics/scoring/tests/test_scoring.py
=> FIX score decomposition when recalibrated outside range of y_pred

pyproject.toml, src/model_diagnostics/calibration/identification.py, src/model_diagnostics/calibration/plots.py, src/model_diagnostics/calibration/tests/test_identification.py, src/model_diagnostics/calibration/tests/test_plots.py
This PR fixes errors that occur with polars 0.20 and extends the tests to cover pl.Enum.
=> FIX polars 0.20

src/model_diagnostics/scoring/scoring.py
Fixes #132
Keyword "columns" in drop is deprecated
=> FIX polars 0.20.4 deprecation warnings

src/model_diagnostics/calibration/plots.py, src/model_diagnostics/calibration/tests/test_plots.py
=> ENH add plotly backend to plot_bias

src/model_diagnostics/_utils/plot_helper.py, src/model_diagnostics/calibration/plots.py, src/model_diagnostics/calibration/tests/test_plots.py, src/model_diagnostics/scoring/plots.py, src/model_diagnostics/scoring/tests/test_plots.py
=> ENH add plotly backend to plot_murphy_diagram

src/model_diagnostics/calibration/plots.py
=> FIX remove argument plot_backend from plot_bias

pyproject.toml, src/model_diagnostics/scoring/scoring.py
Add numpy 2 in test matrix and adapt some code.
=> MNT numpy 2.0.0

docs/gen_ref_pages.py, mkdocs.yml, src/model_diagnostics/calibration/identification.py, src/model_diagnostics/calibration/plots.py, src/model_diagnostics/scoring/plots.py, src/model_diagnostics/scoring/scoring.py
... and fix links and anchor to Notes section
=> DOC make _config part of top level in API reference

README.md, docs/index.md, mkdocs.yml, src/model_diagnostics/_utils/array.py, src/model_diagnostics/_utils/binning.py, src/model_diagnostics/_utils/partial_dependence.py, src/model_diagnostics/_utils/plot_helper.py, src/model_diagnostics/_utils/tests/test_array.py, src/model_diagnostics/_utils/tests/test_partial_dependence.py, src/model_diagnostics/calibration/__init__.py, src/model_diagnostics/calibration/identification.py, src/model_diagnostics/calibration/plots.py, src/model_diagnostics/calibration/tests/test_identification.py, src/model_diagnostics/calibration/tests/test_plots.py
This PR adds
- `model_diagnostics.calibration.compute_bias`
- `model_diagnostics.calibration.plot_marginal`
- Implementation of partial dependence
- More helper functions for indexing/copying/assignment of different dataframe libraries.
=> ENH compute_marginal and plot_marginal

src/model_diagnostics/__init__.py, src/model_diagnostics/_utils/tests/test_partial_dependence.py, src/model_diagnostics/calibration/plots.py, src/model_diagnostics/calibration/tests/test_identification.py, src/model_diagnostics/calibration/tests/test_plots.py
=> MNT remove polars_version

pyproject.toml
See https://github.com/danielfrg/mkdocs-jupyter/issues/212.
=> DOC fix mkdocs-jupyter==0.24.7

docs/javascripts/mathjax.js, mkdocs.yml, pyproject.toml
=> MNT remove polyfill, javascipt updates and mkdocs-material version 9.5.31

src/model_diagnostics/calibration/identification.py, src/model_diagnostics/calibration/tests/test_identification.py
Fixes #155 (because #167 is merged).
=> MNT remove old fix for polars version 0.20

src/model_diagnostics/calibration/identification.py
Missed part in #182. Fixes #155.
=> MNT remove old fix for polars version 0.20 part 2

mkdocs.yml, src/model_diagnostics/_utils/isotonic.py, src/model_diagnostics/_utils/plot_helper.py, src/model_diagnostics/calibration/__init__.py, src/model_diagnostics/calibration/plots.py, src/model_diagnostics/calibration/tests/test_plots.py
Add helper function to ease multiple subplots for `plot_marginal` with plotly backend.
=> ENH add add_marginal_subplot

pyproject.toml, src/model_diagnostics/_utils/binning.py, src/model_diagnostics/_utils/tests/test_isotonic.py, src/model_diagnostics/_utils/tests/test_partial_dependence.py, src/model_diagnostics/calibration/identification.py, src/model_diagnostics/calibration/tests/test_plots.py
This PR fixes a bug and test failures due to new versions of numpy, scipy, polars and scikit-learn.
=> MNT numpy>=2.3, scipy 1.16, polars>=1.29, scikit-learn>=1.7
